# Generated by Django 4.0.4 on 2022-05-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineralDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TectonicConfinement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('depth', models.CharField(max_length=70)),
                ('mineral_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='rest_api.mineraldeposit')),
            ],
        ),
        migrations.AddField(
            model_name='mineraldeposit',
            name='tectonic_confinement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_deposits', to='rest_api.tectonicconfinement'),
        ),
    ]
