# Generated by Django 4.0.4 on 2022-05-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tectonicconfinement',
            name='mineral_deposits',
            field=models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, to='rest_api.mineraldeposit'),
            preserve_default=False,
        ),
    ]
