# Generated by Django 4.0.4 on 2022-05-14 15:28

from django.db import migrations, models
import django.db.models.deletion
import thin.storage.image_storage


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='photo_kern',
            field=models.FileField(blank=True, null=True, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to=''),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to='')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='rest_api.well')),
            ],
        ),
    ]
