# Generated by Django 4.0.4 on 2022-05-14 16:12

from django.db import migrations, models
import django.db.models.deletion
import thin.storage.image_storage


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_well_photo_kern_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='photo',
            field=models.ImageField(blank=True, default=None, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='well',
            name='photo_kern',
            field=models.FileField(blank=True, default=None, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to=''),
        ),
        migrations.CreateModel(
            name='Thin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, default=None, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to='')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thins', to='rest_api.sample')),
            ],
        ),
    ]
