# Generated by Django 4.0.4 on 2022-05-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_sample_photo_alter_well_photo_kern_thin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThinSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thin_sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thin_sections', to='rest_api.thin')),
            ],
        ),
    ]
