# Generated by Django 4.0.4 on 2022-05-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_thinsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thinsection',
            old_name='thin_sections',
            new_name='thin_section',
        ),
    ]
