# Generated by Django 4.0.4 on 2022-05-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_rename_thin_sections_thinsection_thin_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thinsection',
            old_name='thin_section',
            new_name='thin',
        ),
    ]
