# Generated by Django 4.0.4 on 2022-05-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_thinsectionimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thinsectionimage',
            old_name='thin_sections_plots',
            new_name='thin_section',
        ),
    ]
