# Generated by Django 4.0.4 on 2022-05-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_rename_thin_sections_plots_thinsectionimage_thin_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeophysicalSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=25, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_surveys', to='rest_api.well')),
            ],
        ),
    ]
