# Generated by Django 4.0.4 on 2022-05-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_geophysicalsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stratigraphy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=25, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratigraphies', to='rest_api.well')),
            ],
        ),
    ]
