# Generated by Django 4.0.4 on 2022-05-14 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GranulometricAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_more0_25', models.FloatField()),
                ('k_01_025', models.FloatField()),
                ('k_005_01', models.FloatField()),
                ('k_005_001', models.FloatField()),
                ('k_less_0_01', models.FloatField()),
                ('med_dim', models.FloatField()),
                ('k_trusk', models.FloatField()),
                ('st_sort', models.FloatField()),
                ('degree_of_porosity', models.FloatField()),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thin_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gran_analyses', to='geo.thinsection')),
            ],
        ),
    ]
