# Generated by Django 4.0.4 on 2022-05-15 18:36

from django.db import migrations, models
import django.db.models.deletion
import thin.storage.image_storage


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granulometric_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.granulometricanalysis')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.well')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, null=True, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to='')),
                ('image_type', models.CharField(choices=[('CLR', 'color'), ('OV', 'overlay')], default=None, max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.report')),
                ('thin_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.thinsection')),
            ],
        ),
    ]
