# Generated by Django 4.0.4 on 2022-05-14 19:17

from django.db import migrations, models
import django.db.models.deletion
import thin.storage.image_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineralDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, default=None, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TectonicConfinement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Thin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, default=None, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to='')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thins', to='geo.sample')),
            ],
        ),
        migrations.CreateModel(
            name='ThinSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thin_sections', to='geo.thin')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('depth', models.CharField(max_length=70)),
                ('photo_kern', models.FileField(blank=True, default=None, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to='')),
                ('mineral_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='geo.mineraldeposit')),
            ],
        ),
        migrations.CreateModel(
            name='ThinSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('image', models.FileField(blank=True, default=None, storage=thin.storage.image_storage.ClientDocsStorage(), upload_to='')),
                ('thin_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='geo.thinsection')),
            ],
        ),
        migrations.CreateModel(
            name='Stratigraphy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=25, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratigraphies', to='geo.well')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='geo.well'),
        ),
        migrations.AddField(
            model_name='mineraldeposit',
            name='tectonic_confinement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_deposits', to='geo.tectonicconfinement'),
        ),
        migrations.CreateModel(
            name='GeophysicalSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=25, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_surveys', to='geo.well')),
            ],
        ),
    ]
